name: shopsy
description: A Flutter e-commerce mobile application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

workspace:
  - packages/repository
  - packages/storage

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  repository: any
  storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - lib/core/data/
